### ISSUE TITLE
Pre-process dataset and pytorch example

### ISSUE THREAD

**Issue by wq1999** [andreasMazur/geoconv#4]
Hello, this work is very nice!! 
I only have point cloud data(N*3, N points with xyz coordinate), what should i do if i want to apply geoconv on my data for prediction task with pytorch?

**Comment by andreasMazur** [comment]
Hello! Thanks for trying out GeoConv.
As of yet, GeoConv's preprocessing utility requires you to have triangle meshes. If you have pointcloud-data, you could try to first convert that data to triangle meshes using surface reconstruction techniques:

https://www.open3d.org/docs/latest/tutorial/Advanced/surface_reconstruction.html

Afterwards, check whether you have manifold-meshes:

https://www.open3d.org/docs/latest/python_api/open3d.geometry.TriangleMesh.html#open3d.geometry.TriangleMesh.get_non_manifold_edges

Otherwise you will not be able to compute GPC-systems properly.

Lastly,  you should be able to preprocess your shapes as described by the provided examples in the `geoconv_examples`-folder.

Best of luck with your experiments!
